name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: "checkoutする"
      uses: actions/checkout@v4
    - name: "docker buildxが使えるようにする"
      uses: docker/setup-buildx-action@v3
    # NOTE: ecr-loginなどに切り替えることで、別サービスへのプッシュも可能です
    - name: "ghcr.ioにログインする"
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: "メタデータを作成する"
      id: meta # 後段で参照できるようにoutputsに登録する
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/re-x-inc/kiwi
        tags: |
          type=raw,value=latest
          type=sha,prefix=,suffix=,format=short
    - name: "コンテナイメージをビルドしてghcr.ioにコンテナイメージをpushする"
      uses: docker/build-push-action@v5
      with:
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }} # 前ステップで設定したタグを参照する
        labels: ${{ steps.meta.outputs.labels }} # 前ステップで設定したラベルを参照する
